baseURL = 'https://example.org/'
languageCode = 'en'
title = 'My New Hugo Site'
hasCJKLanguage = true

[build]
  [build.buildStats]
    enable = true

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.cjk]
      enable = true
      eastAsianLineBreaks = true
      escapedSpace = true

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.120.0"
