baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
hasCJKLanguage = true

# GA Tracking ID
googleAnalytics = ""

# comments
# https://gohugo.io/templates/internal/#disqus
# disqusShortname = "your-disqus-shortname"
disqusShortname = ""

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.cjk]
      enable = true
      eastAsianLineBreaks = true
      escapedSpace = true

[params]
  # SEO keywords and description for your site.
  keywords = "hugo, tailwind, tailwindcss, hugo theme, hugo theme tailwind"
  subtitle = "Example site for hugo-theme-tailwind"

  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  toc = true

  [params.header]
    logo = "https://placehold.co/512/webp"

  [params.footer]
    since = 2023
    poweredby = true

  [params.taxonomies.icons]
    categories = "category-2"
    tags = "hash"

  # giscus is comments system powered by GitHub Discussions
  # generate configurations from https://giscus.app/
  [params.giscus]
    enabled = false
    repo = "your-repo-name"
    repoID = "your-repo-id"
    category = "your-category"
    categoryID = "your-category-id"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    lang = "en"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.84.2"
