baseURL = "https://gohugo.io"
title = "Hugo Theme Tailwind Example Site"
author = "Xiaoliang Wang"
copyright = "Xiaoliang Wang"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
theme = "hugo-theme-tailwind"

[markup]
  _merge = "deep"

[params]
  # SEO keywords and description for your site.
  keywords = "hugo, tailwind, tailwindcss, hugo theme, hugo theme tailwind"
  subtitle = "Example site for hugo-theme-tailwind"

  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "post"

  [params.header]
    logo = "logo.webp"

  [params.footer]
    since = 2023
    poweredby = true

  # giscus is comments system powered by GitHub Discussions
  # generate configurations from https://giscus.app/
  [params.giscus]
    enabled = true
    repo = "tomowang/hugo-theme-tailwind"
    repoID = "R_kgDOKjVJHA"
    category = "Announcements"
    categoryID = "DIC_kwDOKjVJHM4CafqS"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    lang = "en"

  [params.social_media]
    [[params.social_media.items]]
    enabled = true
    title = 'Facebook'
    icon = 'brand-facebook'
    link = 'https://www.facebook.com/'

    [[params.social_media.items]]
    enabled = true
    title = 'Twitter'
    icon = 'brand-x'
    link = 'https://twitter.com/__PurPleFoX__'

    [[params.social_media.items]]
    enabled = true
    title = 'Instagram'
    icon = 'brand-instagram'
    link = 'https://www.instagram.com/'

    [[params.social_media.items]]
    enabled = true
    title = 'LinkedIn'
    icon = 'brand-linkedin'
    link = 'https://www.linkedin.com/'

    [[params.social_media.items]]
    enabled = true
    title = 'Github'
    icon = 'brand-github'
    link = 'https://github.com/tomowang'

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Post"
    url = "/post/"
    weight = 0

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  # GA Tracking ID
  [services.googleAnalytics]
    ID = "G-75W5D7R0V1"

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

  # comments
  [services.disqus]
    # https://gohugo.io/templates/internal/#disqus
    # disqusShortname = "your-disqus-shortname"
    shortname = ''
